// <auto-generated />
using System;
using BackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190814061502_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("BackEnd.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Bird");

                    b.Property<bool>("Fish");

                    b.Property<bool>("Mammal");

                    b.Property<bool>("Reptile");

                    b.HasKey("Id");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("BackEnd.Models.LivingArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Land");

                    b.Property<bool>("Sea");

                    b.HasKey("Id");

                    b.ToTable("LivingArea");
                });

            modelBuilder.Entity("BackEnd.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Subject");
                });

            modelBuilder.Entity("BackEnd.Models.Animals", b =>
                {
                    b.HasBaseType("BackEnd.Models.Subject");

                    b.Property<int>("AnimalsId");

                    b.Property<int?>("CSId");

                    b.Property<string>("Country");

                    b.Property<string>("Gender");

                    b.Property<int?>("LAId");

                    b.HasIndex("CSId");

                    b.HasIndex("LAId");

                    b.HasDiscriminator().HasValue("Animals");
                });

            modelBuilder.Entity("BackEnd.Models.Animals", b =>
                {
                    b.HasOne("BackEnd.Models.Class", "CS")
                        .WithMany()
                        .HasForeignKey("CSId");

                    b.HasOne("BackEnd.Models.LivingArea", "LA")
                        .WithMany()
                        .HasForeignKey("LAId");
                });
#pragma warning restore 612, 618
        }
    }
}
